### ISSUE TITLE
Support multiple statements at once

### ISSUE THREAD

**Issue by ramnes** [nhoad/aiomanhole#6]
Hey, thanks for the nifty tool!

It seems that sending multiple statements at once isn't supported so far (i.e. `nc ... < foo.py`).

Would you be interested in such a feature? I'd be glad to help if you'd provide a few guidelines on how you'd want to achieve this. :)

**Comment by nhoad** [comment]
Hey! Glad you like it :)

I'm very interested in contributions! What's the issue you're experiencing? I'm not having any trouble passing in multiple statements, e.g.

A server:
```python
import asyncio
import aiomanhole

aiomanhole.start_manhole(port=1234)
asyncio.get_event_loop().run_forever()

```

Client + example output:
```python
$ cat foo.py
print("Hello")
print("World")
a = 1 + 2
print(a)
$ ncat localhost 1234 < foo.py
>>> Hello
>>> World
>>> >>> 3
```

**Comment by ramnes** [comment]
My bad, it does work! I made a programming error (logging with the incorrect level) in my tests and assumed that there was a bug due to the multiple `>>>` printed. :)
